### ISSUE TITLE
el_text set_text()

### ISSUE THREAD

**Issue by NuclearCookie** [litehtml/litehtml#11]
Hi, I'm making a set_text() method in the text element, much in the way you would normally call this from js. However, After i set the text, it seems that the positions have to be updated ( text width will not be the same anymore, stuff like that. Could you give a hint as to what I should call in this method to display the document correctly? 

```c++
void litehtml::el_text::set_text( const tstring& text )
{
    m_text = text;
    parse_styles( true );
    // How do I update the element placement here?
}
```

Thanks in advance @tordex

**Comment by NuclearCookie** [comment]
If you need some extra information, the text is constructed like this
```html
<div id="right_align_text">
    <p id="center_align_p"><text id="elapsed_time_text">0</text></p>
</div>
```

```css
#center_align_p {
    text-align: center;
    font-size:46px;
}

#right_align_text {
    position: fixed;
    right: 100px;
    top: 110px;
}
```

the 0 in the text element will be replaced by a countdown time, in the form of  `02 : 59`. I checked and it looks like the alignment might not be re-calculated correctly..
