### ISSUE TITLE
Cannot get correct document width

### ISSUE THREAD

**Issue by lexxmark** [litehtml/litehtml#128]
Trying to get ideal html document width.

Using this simple code:
```
auto doc = litehtml::document::createFromString("My simple text!", &my_container, &context);
doc->render(maxWidth);
```
I'm getting either _my_container.get_client_rect_ width or _maxWidth_.
I removed all "width:100%;" from master.css with no luck.

After some digging in the code I discovered that _render_box()_ uses _maxWidth_ if _display_ is not inline. So any element with "display: block;" (for example body) will expand ideal width to a  _maxWidth_

How to avoid such an expansion? How you did it in the tooltip project?
Please help.

--Alex

**Comment by tordex** [comment]
Try to use this user style (4th parameter of ``document::createFromString`` ):
``` css
body
{
    margin: 0;
    width:auto;
    height:auto;
}

html
{
    width:auto;
    height:auto;
}
```
`width:auto` is very important here. This allow to render document with width less then maxWidth.
